# This file was generated by GoReleaser. DO NOT EDIT.
cask "khealth" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "61fe63626f20a025fe15da2078bcadc9e5a1faff9f8a9dec66fcdc343dbff01a"
      url "https://github.com/tienkane/khealth/releases/download/v#{version}/khealth_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "466a2f80447b8b55feffb65ab8b24b650973de10844997d1b31cfe23acde6bb9"
      url "https://github.com/tienkane/khealth/releases/download/v#{version}/khealth_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "181ee62948d5b16c598f17220186da65cd45181b4a2947aef1f01d580188012a"
      url "https://github.com/tienkane/khealth/releases/download/v#{version}/khealth_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "21c11a8ad71e5d43652c15865a12b982be59c14615584a5c3a8af913f0f49039"
      url "https://github.com/tienkane/khealth/releases/download/v#{version}/khealth_#{version}_linux_arm64.tar.gz"
    end
  end

  name "khealth"
  desc "Unified health check for your local services in one status table"
  homepage "https://github.com/tienkane/khealth"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khealth"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/khealth"]
    end
  end

  # No zap stanza required

end
