# This file was generated by GoReleaser. DO NOT EDIT.
cask "khealth" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "0cbae9cac9e29e414a0b372d5960168266a2fc66298b4794c433ffa471630529"
      url "https://github.com/tienkane/khealth/releases/download/v#{version}/khealth_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee72885101588f2362c0e72163e2757337b7bb0fae5849bd1f2d2762c69bc895"
      url "https://github.com/tienkane/khealth/releases/download/v#{version}/khealth_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b45d55b88df571b5dacaf369b57d7c706dbd1d7e8da08e21355a45f6ee3acce"
      url "https://github.com/tienkane/khealth/releases/download/v#{version}/khealth_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be08ab836759decb8d6390055cb4851f108eb9273f63070844456937c7c92665"
      url "https://github.com/tienkane/khealth/releases/download/v#{version}/khealth_#{version}_linux_arm64.tar.gz"
    end
  end

  name "khealth"
  desc "Unified health check for your local services in one status table"
  homepage "https://github.com/tienkane/khealth"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khealth"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/khealth"]
    end
  end

  # No zap stanza required

end
