# This file was generated by GoReleaser. DO NOT EDIT.
cask "nodrain" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8eacd2a93381ca20663746486c13403b8a93b32e3e41e078e62c5022f3262137"
      url "https://github.com/tienkane/nodrain/releases/download/v#{version}/nodrain_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9dfe63475abae6760fc8dbee8ba7175c45c6b80e7693a894d10d707e8026c561"
      url "https://github.com/tienkane/nodrain/releases/download/v#{version}/nodrain_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "63afda857433da95340907a398efe5e4b36d6ed1c253bfe52051f840e9c2e296"
      url "https://github.com/tienkane/nodrain/releases/download/v#{version}/nodrain_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "64aaa116b03bc2d4c47623388d2063362b792b4e3789c35cb3f205b8ae00979a"
      url "https://github.com/tienkane/nodrain/releases/download/v#{version}/nodrain_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nodrain"
  desc "Terminal ERC-20 token-approval scanner"
  homepage "https://github.com/tienkane/nodrain"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nodrain"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nodrain"]
    end
  end

  # No zap stanza required

end
