# This file was generated by GoReleaser. DO NOT EDIT.
cask "nodrain" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a3e4fc2a149207a3d04fed764a45ec0ab02d1f44f79afcd8d7b1e6862c7f4239"
      url "https://github.com/tienkane/nodrain/releases/download/v#{version}/nodrain_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "23f9c9d3b0770c8033a709579fdc66b6791e816050865a37e2b94999cb1c3443"
      url "https://github.com/tienkane/nodrain/releases/download/v#{version}/nodrain_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3703b56b73eacece15e06c6281008cf517800ef7b59bcebee60c578514a97fb1"
      url "https://github.com/tienkane/nodrain/releases/download/v#{version}/nodrain_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7498756b99286154848b6721420e9fa2c7689ded78dfbc3bfba95ce83abf1fa3"
      url "https://github.com/tienkane/nodrain/releases/download/v#{version}/nodrain_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nodrain"
  desc "Terminal ERC-20 token-approval scanner"
  homepage "https://github.com/tienkane/nodrain"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nodrain"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nodrain"]
    end
  end

  # No zap stanza required

end
