# This file was generated by GoReleaser. DO NOT EDIT.
cask "portkill" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9271b19a71031ec1e26808c3d1b8cc797dcf83a735a891334a674b0657a77eca"
      url "https://github.com/tienkane/portkill/releases/download/v#{version}/portkill_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7dd881df848b7ca9dc8e70454b6122624b5aa228f980d4084985c912fbef7687"
      url "https://github.com/tienkane/portkill/releases/download/v#{version}/portkill_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ae2acfc8bb7b8fba0477ea9b421709fa5db64a5d220b8a0fca04046e60eaf5f"
      url "https://github.com/tienkane/portkill/releases/download/v#{version}/portkill_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "68aa4d62e370f076d659e0df840339f69e3f0f2fa22c8e273f28f304f189a9ce"
      url "https://github.com/tienkane/portkill/releases/download/v#{version}/portkill_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portkill"
  desc "See what's listening on your ports and kill it"
  homepage "https://github.com/tienkane/portkill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portkill"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portkill"]
    end
  end

  # No zap stanza required

end
