# This file was generated by GoReleaser. DO NOT EDIT.
cask "portkill" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "87a2a3cb9b6d219cb28a4e0295c58a5aa5196afd42012feda4deb4106cc2622b"
      url "https://github.com/tienkane/portkill/releases/download/v#{version}/portkill_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a06c8b44b52df68682c62cf7c7d018bb3f2a157451266832bdc1e658f0f45129"
      url "https://github.com/tienkane/portkill/releases/download/v#{version}/portkill_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "23cacd5e422b1354b619d02d9923675118e1c3919bf31bee4c60582f41f0bd7f"
      url "https://github.com/tienkane/portkill/releases/download/v#{version}/portkill_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ba7f81f50bc626f15475cc92ac88191fe1a19c43d6c1f81225be4b71bf87cf3"
      url "https://github.com/tienkane/portkill/releases/download/v#{version}/portkill_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portkill"
  desc "See what's listening on your ports and kill it"
  homepage "https://github.com/tienkane/portkill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portkill"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portkill"]
    end
  end

  # No zap stanza required

end
