# This file was generated by GoReleaser. DO NOT EDIT.
cask "reel" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "cb52f5969c5afc84392212d1ded74048fa60135c59196b8764112a810493ac2e"
      url "https://github.com/tienkane/reel/releases/download/v#{version}/reel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a69f46678f1cde558a9114a34e5b33549478c529da13abf1e4fca2d02d21489"
      url "https://github.com/tienkane/reel/releases/download/v#{version}/reel_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1f31fb86873406df47b5831750e99ed424838427e26bd0c1bf1e7464dfed2fd4"
      url "https://github.com/tienkane/reel/releases/download/v#{version}/reel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0b3521b02b9793a79585e7791bfb79b3e84adaf556e0ce542017a2a56a0a468"
      url "https://github.com/tienkane/reel/releases/download/v#{version}/reel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "reel"
  desc "Front-end for yt-dlp: download video/audio with a TUI"
  homepage "https://github.com/tienkane/reel"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "reel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reel"]
    end
  end

  # No zap stanza required

end
