# This file was generated by GoReleaser. DO NOT EDIT.
cask "txdecode" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "435ba9d7d57ea2b4b072fe682189496992717d563c20ee116f3fe3a3dc290fc7"
      url "https://github.com/tienkane/txdecode/releases/download/v#{version}/txdecode_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "49e2e41e1b34bcc0ac77d773e58e66bca7c8802ed469dc19eb0adea05fec4244"
      url "https://github.com/tienkane/txdecode/releases/download/v#{version}/txdecode_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40d622eb089934ca76af85151e094e0c058851ef961300ae2948285069287bef"
      url "https://github.com/tienkane/txdecode/releases/download/v#{version}/txdecode_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3728d44832cadb485dd1ac5798cd50172f5af29f073d08fbf66b997aadeac753"
      url "https://github.com/tienkane/txdecode/releases/download/v#{version}/txdecode_#{version}_linux_arm64.tar.gz"
    end
  end

  name "txdecode"
  desc "Decode a transaction's calldata and flag dangerous operations"
  homepage "https://github.com/tienkane/txdecode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "txdecode"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/txdecode"]
    end
  end

  # No zap stanza required

end
