# This file was generated by GoReleaser. DO NOT EDIT.
cask "txdecode" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "07b095f4b82b2c891ee02500eae7414f1444d7eb650753eb037f33fc55ed5dc8"
      url "https://github.com/tienkane/txdecode/releases/download/v#{version}/txdecode_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55019e7706dfd706e9fd1372a718ecfb91f54cb2f5be195d1f8ad39b2b0e5478"
      url "https://github.com/tienkane/txdecode/releases/download/v#{version}/txdecode_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "be4eac4e123c1a3995ade99e1a3db2784219ffe5bbc59ea46f960c38d9834fbf"
      url "https://github.com/tienkane/txdecode/releases/download/v#{version}/txdecode_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ee679dc71563c90486916c49af250d7b5fff4bb574aa169234f4249cb13f1aa"
      url "https://github.com/tienkane/txdecode/releases/download/v#{version}/txdecode_#{version}_linux_arm64.tar.gz"
    end
  end

  name "txdecode"
  desc "Decode a transaction's calldata and flag dangerous operations"
  homepage "https://github.com/tienkane/txdecode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "txdecode"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/txdecode"]
    end
  end

  # No zap stanza required

end
